#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rspec-rails
Version  : 3.3.2
Release  : 7
URL      : https://rubygems.org/downloads/rspec-rails-3.3.2.gem
Source0  : https://rubygems.org/downloads/rspec-rails-3.3.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-cucumber
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
# rspec-rails [![Build Status](https://secure.travis-ci.org/rspec/rspec-rails.svg?branch=master)](http://travis-ci.org/rspec/rspec-rails) [![Code Climate](https://img.shields.io/codeclimate/github/rspec/rspec-rails.svg)](https://codeclimate.com/github/rspec/rspec-rails)
**rspec-rails** is a testing framework for Rails 3.x and 4.x.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rspec-rails-3.3.2
gem spec %{SOURCE0} -l --ruby > rubygem-rspec-rails.gemspec

%build
gem build rubygem-rspec-rails.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rspec-rails-3.3.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/rspec-rails-3.3.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/ActiveRecord/VERSION/cdesc-VERSION.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/ActiveRecord/cdesc-ActiveRecord.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Capybara/cdesc-Capybara.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Matchers/BuiltIn/cdesc-BuiltIn.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Matchers/cdesc-Matchers.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ActiveRecordConfiguration/cdesc-ActiveRecordConfiguration.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ActiveRecordConfiguration/initialize_activerecord_configuration-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/AssertionDelegator/assertion_instance-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/AssertionDelegator/cdesc-AssertionDelegator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/AssertionDelegator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Configuration/cdesc-Configuration.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/ActionController/cdesc-ActionController.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/BypassRescue/cdesc-BypassRescue.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/BypassRescue/rescue_with_handler-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/ClassMethods/controller-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/ClassMethods/controller_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/ClassMethods/name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/ClassMethods/routes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/bypass_rescue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/cdesc-ControllerExampleGroup.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/controller-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/route_available%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/route_defined%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/routes%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ControllerExampleGroup/routes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FeatureCheck/can_check_pending_migrations%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FeatureCheck/can_maintain_test_schema%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FeatureCheck/cdesc-FeatureCheck.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FeatureCheck/has_1_9_hash_syntax%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FeatureCheck/has_action_mailer%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FeatureCheck/has_action_mailer_preview%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FeatureCheck/has_action_mailer_show_preview%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FeatureCheck/has_active_job%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FeatureCheck/has_active_record%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FeatureCheck/has_active_record_migration%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FeatureCheck/type_metatag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FeatureExampleGroup/cdesc-FeatureExampleGroup.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FeatureExampleGroup/visit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FixtureSupport/ActiveSupport/cdesc-ActiveSupport.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/FixtureSupport/cdesc-FixtureSupport.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/HelperExampleGroup/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/HelperExampleGroup/ClassMethods/determine_default_helper_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/HelperExampleGroup/_controller_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/HelperExampleGroup/cdesc-HelperExampleGroup.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/HelperExampleGroup/helper-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/JobExampleGroup/cdesc-JobExampleGroup.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MailerExampleGroup/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MailerExampleGroup/ClassMethods/mailer_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MailerExampleGroup/cdesc-MailerExampleGroup.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeANew/attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeANew/attributes_match%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeANew/cdesc-BeANew.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeANew/failure_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeANew/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeANew/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeANew/unmatched_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeANew/with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeANewRecord/cdesc-BeANewRecord.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeANewRecord/failure_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeANewRecord/failure_message_when_negated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeANewRecord/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeValid/cdesc-BeValid.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeValid/failure_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeValid/failure_message_when_negated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeValid/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/BeValid/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/GenericStatus/cdesc-GenericStatus.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/GenericStatus/description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/GenericStatus/failure_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/GenericStatus/failure_message_when_negated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/GenericStatus/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/GenericStatus/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/GenericStatus/type_codes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/GenericStatus/type_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/GenericStatus/valid_statuses-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/NumericCode/cdesc-NumericCode.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/NumericCode/description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/NumericCode/failure_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/NumericCode/failure_message_when_negated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/NumericCode/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/NumericCode/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/SymbolicStatus/actual_status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/SymbolicStatus/cdesc-SymbolicStatus.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/SymbolicStatus/compute_status_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/SymbolicStatus/description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/SymbolicStatus/expected_status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/SymbolicStatus/failure_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/SymbolicStatus/failure_message_when_negated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/SymbolicStatus/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/SymbolicStatus/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/SymbolicStatus/pp_actual-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/SymbolicStatus/pp_expected-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/SymbolicStatus/pp_status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/SymbolicStatus/set_expected_code%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/as_test_response-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/as_test_response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/cdesc-HaveHttpStatus.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/invalid_response_type_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/HaveHttpStatus/matcher_for_status-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RedirectTo/RedirectTo/cdesc-RedirectTo.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RedirectTo/RedirectTo/failure_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RedirectTo/RedirectTo/failure_message_when_negated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RedirectTo/RedirectTo/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RedirectTo/RedirectTo/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RedirectTo/cdesc-RedirectTo.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RedirectTo/redirect_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RenderTemplate/RenderTemplateMatcher/cdesc-RenderTemplateMatcher.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RenderTemplate/RenderTemplateMatcher/failure_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RenderTemplate/RenderTemplateMatcher/failure_message_when_negated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RenderTemplate/RenderTemplateMatcher/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RenderTemplate/RenderTemplateMatcher/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RenderTemplate/cdesc-RenderTemplate.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RenderTemplate/have_rendered-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RenderTemplate/render_template-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/BeRoutableMatcher/cdesc-BeRoutableMatcher.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/BeRoutableMatcher/description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/BeRoutableMatcher/failure_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/BeRoutableMatcher/failure_message_when_negated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/BeRoutableMatcher/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/BeRoutableMatcher/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/RouteHelpers/cdesc-RouteHelpers.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/RouteToMatcher/cdesc-RouteToMatcher.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/RouteToMatcher/description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/RouteToMatcher/failure_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/RouteToMatcher/failure_message_when_negated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/RouteToMatcher/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/RouteToMatcher/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/be_routable-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/cdesc-RoutingMatchers.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/RoutingMatchers/route_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/be_a_new-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/be_new_record-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/be_valid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/cdesc-Matchers.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Matchers/have_http_status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MinitestAssertionAdapter/AssertionDelegator/cdesc-AssertionDelegator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MinitestAssertionAdapter/ClassMethods/assertion_method_names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MinitestAssertionAdapter/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MinitestAssertionAdapter/ClassMethods/define_assertion_delegators-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MinitestAssertionAdapter/assertion_delegator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MinitestAssertionAdapter/cdesc-MinitestAssertionAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MinitestCounters/assertions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MinitestCounters/cdesc-MinitestCounters.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MinitestLifecycleAdapter/after_setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MinitestLifecycleAdapter/after_teardown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MinitestLifecycleAdapter/before_setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MinitestLifecycleAdapter/before_teardown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/MinitestLifecycleAdapter/cdesc-MinitestLifecycleAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ModelExampleGroup/cdesc-ModelExampleGroup.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/RailsExampleGroup/cdesc-RailsExampleGroup.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Railtie/cdesc-Railtie.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Railtie/config_default_preview_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Railtie/config_preview_path%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Railtie/setup_preview_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Railtie/supports_action_mailer_previews%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/RequestExampleGroup/app-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/RequestExampleGroup/cdesc-RequestExampleGroup.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/RoutingExampleGroup/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/RoutingExampleGroup/ClassMethods/routes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/RoutingExampleGroup/cdesc-RoutingExampleGroup.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/RoutingExampleGroup/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/RoutingExampleGroup/routes%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/RoutingExampleGroup/routes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/SetupAndTeardownAdapter/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/SetupAndTeardownAdapter/ClassMethods/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/SetupAndTeardownAdapter/ClassMethods/teardown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/SetupAndTeardownAdapter/cdesc-SetupAndTeardownAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/SetupAndTeardownAdapter/method_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/SetupAndTeardownAdapter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/TestUnitAssertionAdapter/assertion_delegator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/TestUnitAssertionAdapter/cdesc-TestUnitAssertionAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/VERSION/cdesc-VERSION.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/Version/cdesc-Version.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewAssigns/_assigns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewAssigns/_encapsulated_assigns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewAssigns/assign-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewAssigns/cdesc-ViewAssigns.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewAssigns/view_assigns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ClassMethods/_default_helper-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ClassMethods/_default_helpers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ExampleMethods/_controller_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ExampleMethods/_default_render_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ExampleMethods/_include_controller_helpers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ExampleMethods/_inferred_action-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ExampleMethods/_path_parts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ExampleMethods/cdesc-ExampleMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ExampleMethods/params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ExampleMethods/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ExampleMethods/response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ExampleMethods/stub_template-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ExampleMethods/template-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/ExampleMethods/view-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewExampleGroup/cdesc-ViewExampleGroup.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/ActionView/cdesc-ActionView.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/ClassMethods/render_views%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/ClassMethods/render_views-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/EmptyTemplateHandler/call-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/EmptyTemplateHandler/cdesc-EmptyTemplateHandler.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/EmptyTemplatePathSetDecorator/cdesc-EmptyTemplatePathSetDecorator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/EmptyTemplatePathSetDecorator/find_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/EmptyTemplatePathSetDecorator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/EmptyTemplatePathSetDecorator/original_path_set-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/EmptyTemplates/_path_decorator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/EmptyTemplates/append_view_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/EmptyTemplates/cdesc-EmptyTemplates.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/EmptyTemplates/prepend_view_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/cdesc-ViewRendering.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/controller-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/ViewRendering/render_views%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/disable_testunit_autorun-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/infer_spec_type_from_file_location%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/initialize_configuration-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/render_views%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/render_views%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Rails/render_views-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/Support/cdesc-Support.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/RSpec/cdesc-RSpec.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rails/Generators/GeneratedAttribute/cdesc-GeneratedAttribute.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rails/Generators/GeneratedAttribute/input_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rails/Generators/cdesc-Generators.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/Base/Rails/VERSION/cdesc-VERSION.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/Base/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/Base/module_namespacing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/Base/source_root-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ControllerGenerator/cdesc-ControllerGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ControllerGenerator/generate_controller_spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ControllerGenerator/generate_view_specs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/FeatureGenerator/cdesc-FeatureGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/FeatureGenerator/generate_feature_spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/HelperGenerator/cdesc-HelperGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/HelperGenerator/generate_helper_spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/InstallGenerator/cdesc-InstallGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/InstallGenerator/copy_rails_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/InstallGenerator/copy_spec_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/InstallGenerator/generate_rspec_init-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/InstallGenerator/remove_warnings_configuration-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/InstallGenerator/replace_generator_command-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/InstallGenerator/source_root-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/IntegrationGenerator/cdesc-IntegrationGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/IntegrationGenerator/generate_request_spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/JobGenerator/cdesc-JobGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/JobGenerator/create_job_spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/MailerGenerator/cdesc-MailerGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/MailerGenerator/generate_fixtures_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/MailerGenerator/generate_mailer_spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/MailerGenerator/generate_preview_files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ModelGenerator/cdesc-ModelGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ModelGenerator/create_fixture_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ModelGenerator/create_model_spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ModelGenerator/missing_fixture_replacement%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ObserverGenerator/cdesc-ObserverGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ObserverGenerator/generate_observer_spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/RequestGenerator/cdesc-RequestGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/banner-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/cdesc-ScaffoldGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/copy_view-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/formatted_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/generate_controller_spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/generate_routing_spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/generate_view_specs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/mock_file_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/ns_file_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/ns_parts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/ns_table_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/raw_value_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/should_receive-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/stub-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/stub_or_should_chain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ScaffoldGenerator/value_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ViewGenerator/cdesc-ViewGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/ViewGenerator/create_view_specs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/Generators/cdesc-Generators.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/Rspec/cdesc-Rspec.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/lib/generators/rspec/mailer/templates/page-fixture.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-rails-3.3.2/ri/lib/rspec/rails/tasks/page-rspec_rake.ri
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/.document
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/Capybara.md
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/Changelog.md
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/License.txt
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/README.md
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/controller/controller_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/controller/templates/controller_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/controller/templates/view_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/feature/feature_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/feature/templates/feature_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/helper/helper_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/helper/templates/helper_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/install/install_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/install/templates/spec/rails_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/integration/integration_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/integration/templates/request_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/job/job_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/job/templates/job_spec.rb.erb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/mailer/mailer_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/mailer/templates/fixture
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/mailer/templates/mailer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/mailer/templates/preview.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/model/model_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/model/templates/fixtures.yml
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/model/templates/model_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/observer/observer_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/observer/templates/observer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/request/request_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/scaffold/scaffold_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/scaffold/templates/controller_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/scaffold/templates/edit_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/scaffold/templates/index_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/scaffold/templates/new_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/scaffold/templates/routing_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/scaffold/templates/show_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/view/templates/view_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/generators/rspec/view/view_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec-rails.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/active_record.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/adapters.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/configuration.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/example.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/example/controller_example_group.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/example/feature_example_group.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/example/helper_example_group.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/example/job_example_group.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/example/mailer_example_group.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/example/model_example_group.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/example/rails_example_group.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/example/request_example_group.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/example/routing_example_group.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/example/view_example_group.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/extensions.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/extensions/active_record/proxy.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/feature_check.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/fixture_support.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/matchers.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/matchers/be_a_new.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/matchers/be_new_record.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/matchers/be_valid.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/matchers/have_http_status.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/matchers/have_rendered.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/matchers/redirect_to.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/matchers/relation_match_array.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/matchers/routing_matchers.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/tasks/rspec.rake
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/vendor/capybara.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/view_assigns.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec/rails/view_rendering.rb
/usr/lib64/ruby/gems/2.2.0/specifications/rspec-rails-3.3.2.gemspec
